### ISSUE TITLE
Unable to find '/home/ubuntu/.ssh/id_rsa.pub' in expected paths

### ISSUE THREAD

**Issue by Chabane** [davidkbainbridge/k8s-playground#7]
Hi,

Thanks for sharing!

I have this error when I run : vagrant provision

```
[WARNING]: Unable to find '/home/ubuntu/.ssh/id_rsa.pub' in expected paths.

fatal: [192.168.33.21]: FAILED! => {"failed": true, "msg": "could not locate file in lookup: /home/ubuntu/.ssh/id_rsa.pub"}

```

```
- name: Ensure SSH Directories
  file:
    path: "{{home}}/.ssh"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Copy SSH Key Files
  copy:
    src: files/{{ item }}
    dest: "{{home}}/.ssh/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub
    - config

- name: Ensure Authorized SSH Key
  become: yes
  authorized_key:
    user: ubuntu
    key:  "{{ lookup('file', item) }}"
    state: present
  with_file:
    - "{{home}}/.ssh/id_rsa.pub"
```
Do you have any idea about this error? I found nothing useful via Google.

Thanks
